config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: "homes#top"
  get '/search', to: 'searches#searche'
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource:favorites,only:[:create, :destroy]
    resources:book_comments,only:[:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource:relationship,only:[:create, :destroy]
    get "relationships/follow_list"
    get "relationships/follower_list"
  end
  # get '/search'=>'searches#search',as:"search"
  # get '/search', to: 'searchs#search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}

  belongs_to:user
  has_many:favorites,dependent: :destroy
  has_many:book_comments,dependent: :destroy
  # def get_profile_image
  #   (profile_image.attached?) ? profile_image : 'no_image.jpg'
  # end


  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to:user
  belongs_to:book
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to:user
  belongs_to:book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to:follower,class_name: "User"
  belongs_to:followed,class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many:books,dependent: :destroy
  has_many:favorites,dependent: :destroy
  has_many:book_comments,dependent: :destroy

  has_many:follower,class_name: "Relationship" , foreign_key: "follower_id",dependent: :destroy
  has_many:followed,class_name: "Relationship" , foreign_key: "followed_id",dependent: :destroy

  has_many:followers,through: :follower,source: :followed
  has_many:followeds,through: :followed,source: :follower

  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction,length:{ maximum: 50 }



  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except:[:top, :about]
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    comment = BookComment.new(comment_params)
    comment.user_id = current_user.id
    comment.book_id = @book.id
    comment.save
    redirect_to book_path(@book.id)
  end
  def destroy
    comment = BookComment.find(params[:id])
    comment.destroy
    redirect_to book_path(params[:book_id])
  end
  private
  def comment_params
    params.require(:book).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit]
  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @books = Book.new
    @comment = BookComment.new
  end

  def index
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user_id == current_user.id
      @book = Book.new
      @books = Book.all
      redirect_to books_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
 def create
   book = Book.find(params[:book_id])
   favorite = Favorite.new
   favorite.user_id = current_user.id
   favorite.book_id = book.id
   favorite.save
   redirect_to books_path
 end
 def destroy
   book = Book.find(params[:book_id])
   favorite = current_user.favorites.find_by(book_id: book.id)
   favorite.destroy
   redirect_to books_path
 end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def follow_list
    user = User.find(params[:user_id])
    @follower_list = user.followers
  end
  def follower_list
    user = User.find(params[:user_id])
    @follower_list = user.followeds
  end

  def create
    followed = User.find(params[:user_id])
    relationship = Relationship.new
    relationship.follower_id = current_user.id
    relationship.followed_id = followed.id
    relationship.save
    
    redirect_to request.referer
   
  end
  def destroy
    user = User.find(params[:user_id])
    current_user.follower.find_by(followed_id: user.id).destroy

    # "https://d45db844a3944142abaa224a36ba527e.vfs.cloud9.us-east-1.amazonaws.com/users"
    redirect_to request.referer
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def searche
    @model = params["model"]
    @method = params["method"]
    @content = params["content"]
    @records = search_for(@model,@content,@method)
  end
  private
  def search_for(model,content,method)
   if model == 'User'
     if method == 'perfect'
       User.where(name: content)
     elsif method == 'Partially'
       User.where('name LIKE ?','%'+content+'%')
     elsif method == 'front'
       User.where('name LIKE ?',content+'%')
     elsif method == 'back'
       User.where('name LIKE ?','%'+content)
     end
   elsif model == 'Book'
     if method == 'perfect'
       Book.where(title: content)
     elsif method == 'Partially'
       Book.where('title LIKE ?','%'+content+'%')
     elsif method == 'front'
       Book.where('title LIKE ?',content+'%')
     elsif method == 'back'
       Book.where('title LIKE ?','%'+content)
     end
   end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:update, :edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_with model: book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image, size: '50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <td>
           <% if book.favorited_by?(current_user) %>
            <%= link_to book_favorites_path(book.id),method: :delete do %>
             💗<%= book.favorites.count %>いいね
            <% end %>
           <% else %>
            <%= link_to book_favorites_path(book.id),method: :post do %>
             💛<%= book.favorites.count %>いいね
            <% end %>
           <% end %>
        </td>
        <td>
          コメント<%= book.book_comments.count %>件
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<% if @book.errors.any? %>
        <%= @book.errors.count %>件のerror発生
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      <% end %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book, class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>

      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <% if @book.errors.any? %>
       <%= @book.errors.count %>件のerror
       <% @book.errors.full_messages.each do |message| %>
         <li><%= message %></li>
       <% end %>
      <% end %>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @books %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td><%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image, size:"100x100" %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
          <td>
            <% if @book.favorited_by?(current_user) %>
              <%= link_to  book_favorites_path(@book.id),method: :delete  do %>
                💗<%= @book.favorites.count %>いいね
              <% end %>
            <% else %>
              <%= link_to book_favorites_path(@book.id),method: :post do %>
                💛<%= @book.favorites.count %>いいね
              <% end %>
            <% end %>
          </td>
            <td>
              <% if @book.user_id == current_user.id %>
                <%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %>
              <% end %>
            </td>
            <td>
              <% if @book.user_id == current_user.id %>
                <%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%>
              <% end %>
            </td>
            <td>
              コメント<%= @book.book_comments.count %>件
            </td>
        </tr>
      </table>
      <h3>コメント一覧</h3>
      <% @book.book_comments.each do |comment| %>
        <table class="table">
          <tr>
            <td style="width: 30%">
              <%= link_to user_path(comment.user.id) do %>
                <%= image_tag comment.user.get_profile_image, size:"50x50" %><br>
                <%= comment.user.name %>
              <% end %>
            </td>
            <td><%= comment.comment %></td>
            <td>
              <%= link_to"Delete",book_book_comment_path(comment.book,comment),method: :delete,class:"btn btn-danger" %>
            </td>
          </tr>
        </table>
      <% end %>

      <%= form_with model: [@comment, @book],url: book_book_comments_path(@book.id),method: :post do |f| %>
        <%= f.text_area :comment,rows: '5',placeholder:"コメントはここに",class:"form-control" %>
        <%= f.submit"送信" %>
      <% end %>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class='container'>
  <div class='row'>
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to 'Log in',new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <%= link_to 'Sign Up',new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/relationships/follow_list.html.erb
<div class="container">
 <h1>Follow user</h1>
 <% @follower_list.each do |follower| %>
  <table class="table">
    <tr>
     <td><%= image_tag follower.get_profile_image,size:"50x50" %></td>
     <td>
     <%= follower.name %>
    </td>
    <td>
     フォロー数：<%= follower.followers.count %>
    </td>
    <td>
      フォロワー数：<%= follower.followeds.count %>
    </td>
    <td>
      <%= link_to"Show",user_path(follower.id) %>
    </td>
   </tr>
  </table>

 <% end %>
</div>

app/views/relationships/follower_list.html.erb
<div class="container">
  <h1>Follower user</h1>
  <% @follower_list.each do |follower| %>
  <table class="table">
    <tr>
      <td><%= image_tag follower.get_profile_image,size:"50x50" %></td>
      <td>
        <%= follower.name %>
      </td>
      <td>
        フォロー数<%= follower.followers.count %>
      </td>
      <td>
        フォロワー数<%= follower.followeds.count %>
      </td>
      <td><%= link_to"Show",user_path(follower.id) %></td>
    </tr>
  </table>

  <% end %>
  </div>

app/views/searches/_searche.html.erb
  <%= form_with url: search_path ,method: :get do |f| %>
  <%= f.text_field :content %>
  <%= f.select :model,options_for_select({"User"=>"User","Book"=>"Book"}) %>
  <%= f.select :method,options_for_select({"完全一致"=>"perfect","部分一致"=>"Partially","前方一致"=>"front","後方一致"=>"back"}) %>
  <%= f.submit'検索' %>
  <% end %>

app/views/searches/searche.html.erb
<table class="table">
<% if @model == 'Book' %>
 <tr>
   <td></td>
   <td>Title</td>
   <td>Opinion</td>
 </tr>
  <% @records.each do |record| %>
  <tr>
   <td><%= image_tag record.user.get_profile_image,size:'100x100' %></td>
   <td>
    <%= link_to book_path(record.id) do %>
      <%= record.title %>
    <% end %>
   </td>
   <td><%= record.body %></td>
  </tr>
  <% end %>
<% elsif %>
  <% @records.each do |record| %>
  <tr>
   <td><%= image_tag record.get_profile_image,size:'100x100' %></td>
   <td>
     <%= link_to user_path(record.id) do %>
       <%= record.name %>
     <% end %>
   </td>
   <td><%= record.introduction %></td>
  </tr>
  <% end %>
<% end %>
</table>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数<%= user.follower.count %></td>
        <td>フォロワー数<%= user.followed.count %></td>
        <% unless user.id == current_user.id %>
          <% if current_user.follower.exists?(followed_id: user.id) %>
            <td><%= link_to "フォロー解除",user_relationship_path(user.id),method: :delete %></td>
          <% else %>
            <td><%= link_to "フォロー",user_relationship_path(user.id),method: :post %></td>
          <% end %>
        <% else %>
            <td></td>
        <% end %>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th></th>
    <th>
      <%= link_to user_relationships_follow_list_path(user.id) do %>
        フォロー<%= user.followers.count %>件
      <% end %>
    </th>
  </tr>
  <tr>
    <th></th>
    <th>
      <%= link_to user_relationships_follower_list_path(user.id) do %>
        フォロワー<%= user.followeds.count %>件
      <% end %>
    </th>
  </tr>
</table>
  <% unless current_user.id == user.id %>
    <% if current_user.follower.exists?(followed_id: user.id) %>
      <buton class="btn btn-success mb-4"><%= link_to"フォロー解除",user_relationship_path(user.id),method: :delete,class:"text-white" %></buton>
    <% else %>
      <buton class="btn btn-success mb-4"><%= link_to"フォロー",user_relationship_path(user.id),method: :post,class:"text-white" %></buton>
    <% end %>
  <% end %>


<div class='row'>
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>

     <div class="form-group">
        <%= f.label :profile_image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
     <h2>User info</h2>
     <%= render 'info', user: current_user %>
     <h2 class="mt-3">New book</h2>
     <%= render 'books/form',book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
     <h2>Users</h2>
     <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>